name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Which dir am I in bitch
      run: ls
    - name: Install Deps
      run: bash ./cocos2d/install-deps-linux.sh
    - name: Cmake
      run: cmake -B build
    - name: Make
      run: cd build
    - name: Make2
      run: make
